// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxwddyhpucgbbomfoiyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4d2RkeWhwdWNnYmJvbWZvaXlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTM2NzYsImV4cCI6MjA2MDAyOTY3Nn0.qdVlkMl9r-47bFyjbHa0UHwXd0MHdyZpuBCunnA6Oj4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);